plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.tanil.netfood'
    compileSdk 35

    defaultConfig {
        applicationId "com.tanil.netfood"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation 'com.google.android.gms:play-services-ads:22.0.0'

    // CameraX Core
    implementation 'androidx.camera:camera-core:1.4.0'

    // CameraX Lifecycle (Kamera yaşam döngüsü için)
    implementation 'androidx.camera:camera-lifecycle:1.4.0'

    // CameraX View (PreviewView için gerekli)
    implementation 'androidx.camera:camera-view:1.4.0'

    // CameraX Camera2 (Camera2 API'yi kullanmak için gerekli)
    implementation 'androidx.camera:camera-camera2:1.4.0'

    implementation 'com.google.mlkit:text-recognition:16.0.0'

    implementation 'com.android.volley:volley:1.2.1'

    implementation "com.airbnb.android:lottie:6.0.0"

}